import { type IOffer } from "@/components/Offers/OfferCard";

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
] as const;

export const OFFERS: IOffer[] = [
  {
    id: "o1",
    image: "/images/monthly/Sep-01.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o2",
    image: "/images/monthly/Sep-02.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o3",
    image: "/images/monthly/Sep-03.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o4",
    image: "/images/monthly/Sep-04.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o5",
    image: "/images/monthly/Sep-05.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o6",
    image: "/images/monthly/Sep-06.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o7",
    image: "/images/monthly/Sep-07.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o8",
    image: "/images/monthly/Sep-08.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o9",
    image: "/images/monthly/Sep-09.png",
    alt: "Poured soy candle",
  },
  {
    id: "o10",
    image: "/images/monthly/Sep-10.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o11",
    image: "/images/monthly/Sep-11.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o12",
    image: "/images/monthly/Sep-12.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o13",
    image: "/images/monthly/Sep-13.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o14",
    image: "/images/monthly/Sep-14.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o15",
    image: "/images/monthly/Sep-15.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o16",
    image: "/images/monthly/Sep-16.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o17",
    image: "/images/monthly/Sep-17.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o18",
    image: "/images/monthly/Sep-18.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o19",
    image: "/images/monthly/Sep-19.png",
    alt: "Poured soy candle",
  },
  {
    id: "o20",
    image: "/images/monthly/Sep-20.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o21",
    image: "/images/monthly/Sep-21.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o22",
    image: "/images/monthly/Sep-22.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o23",
    image: "/images/monthly/Sep-23.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o24",
    image: "/images/monthly/Sep-24.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o25",
    image: "/images/monthly/Sep-25.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o26",
    image: "/images/monthly/Sep-26.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o27",
    image: "/images/monthly/Sep-27.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o28",
    image: "/images/monthly/Sep-28.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o29",
    image: "/images/monthly/Sep-29.png",
    alt: "Poured soy candle",
  },
  {
    id: "o30",
    image: "/images/monthly/Sep-30.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o31",
    image: "/images/monthly/Sep-31.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o32",
    image: "/images/monthly/Sep-32.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o33",
    image: "/images/monthly/Sep-33.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o34",
    image: "/images/monthly/Sep-34.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o35",
    image: "/images/monthly/Sep-35.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o36",
    image: "/images/monthly/Sep-36.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o37",
    image: "/images/monthly/Sep-37.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o38",
    image: "/images/monthly/Sep-38.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o39",
    image: "/images/monthly/Sep-39.png",
    alt: "Poured soy candle",
  },
  {
    id: "o40",
    image: "/images/monthly/Sep-40.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o41",
    image: "/images/monthly/Sep-41.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o42",
    image: "/images/monthly/Sep-42.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o43",
    image: "/images/monthly/Sep-43.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o44",
    image: "/images/monthly/Sep-44.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o45",
    image: "/images/monthly/Sep-45.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o46",
    image: "/images/monthly/Sep-46.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o47",
    image: "/images/monthly/Sep-47.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o48",
    image: "/images/monthly/Sep-48.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o49",
    image: "/images/monthly/Sep-49.png",
    alt: "Poured soy candle",
  },
  {
    id: "o50",
    image: "/images/monthly/Sep-50.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o51",
    image: "/images/monthly/Sep-51.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o52",
    image: "/images/monthly/Sep-52.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o53",
    image: "/images/monthly/Sep-53.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o54",
    image: "/images/monthly/Sep-54.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o55",
    image: "/images/monthly/Sep-55.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o56",
    image: "/images/monthly/Sep-56.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o57",
    image: "/images/monthly/Sep-57.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o58",
    image: "/images/monthly/Sep-58.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o59",
    image: "/images/monthly/Sep-59.png",
    alt: "Poured soy candle",
  },
  {
    id: "o60",
    image: "/images/monthly/Sep-60.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o61",
    image: "/images/monthly/Sep-61.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o62",
    image: "/images/monthly/Sep-62.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o63",
    image: "/images/monthly/Sep-63.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o64",
    image: "/images/monthly/Sep-64.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o65",
    image: "/images/monthly/Sep-65.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o66",
    image: "/images/monthly/Sep-66.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o67",
    image: "/images/monthly/Sep-67.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o68",
    image: "/images/monthly/Sep-68.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
  {
    id: "o69",
    image: "/images/monthly/Sep-69.png",
    alt: "Poured soy candle",
  },
  {
    id: "o70",
    image: "/images/monthly/Sep-70.png",
    alt: "Pressed powder blush",
    showDetails: false,
  },
  {
    id: "o71",
    image: "/images/monthly/Sep-71.png",
    alt: "Wool trench coat on a hanger",
    showDetails: false,
    name: "Wool Trench Coat",
  },
  {
    id: "o72",
    image: "/images/monthly/Sep-72.png",
    alt: "Ceramic table lamp",
  },
  {
    id: "o73",
    image: "/images/monthly/Sep-73.png",
    alt: "Wireless earbuds in charging case",
    showDetails: false,
  },
  {
    id: "o74",
    image: "/images/monthly/Sep-74.png",
    alt: "Skincare serum bottle",
  },
  {
    id: "o75",
    image: "/images/monthly/Sep-75.png",
    alt: "Leather tote bag",
    showDetails: false,
    name: "Leather Tote",
  },
  {
    id: "o76",
    image: "/images/monthly/Sep-76.png",
    alt: "Hand-thrown ceramic vase",
  },
  {
    id: "o77",
    image: "/images/monthly/Sep-77.png",
    alt: "Minimal wristwatch",
  },
  {
    id: "o78",
    image: "/images/monthly/Sep-78.png",
    alt: "Silk scarf folded flat",
    showDetails: false,
  },
];